# .circleci/config.yml
defaults: &defaults
  docker:
    - image: circleci/node:8-browsers
      environment:
        JOBS: 2
  working_directory: ~/example-percy-puppeteer

orbs:
  percy: percy/agent@volatile

version: 2.1
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .

  install_dependencies:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-deps-{{ .Branch }}-
            - v1-deps-
      - run:
          name: npm install
          command: sudo npm install -g @percy/agent && npm install --non-interactive
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  run_tests:
    <<: *defaults
    parallelism: 2
    steps:
      - attach_workspace:
          at: .
      - run: echo 'export PATH=~/example-percy-puppeteer/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests
          command: npm run test:parallel:${CIRCLE_NODE_INDEX}

workflows:
  test_and_deploy:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - run_tests:
          requires:
            - install_dependencies
      - percy/finalize_all:
          requires:
            - run_tests
