# .circleci/config.yml
defaults: &defaults
  docker:
    - image: circleci/node:8-browsers
      environment:
        JOBS: 2
  working_directory: ~/example-percy-puppeteer

orbs:
  percy: percy/agent@volatile

version: 2.1
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout

  install_dependencies:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-deps-{{ .Branch }}-
            - v1-deps-
      - run:
          name: yarn install
          command: yarn global add @percy/agent && yarn install --non-interactive
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  run_tests:
    <<: *defaults
    parallelism: 2
    steps:
      - run: echo 'export PATH=~/example-percy-puppeteer/node_modules/.bin:$PATH' >> $BASH_ENV
      - run:
          name: Run Tests
          command: yarn test

workflows:
  test_and_deploy:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - run_tests:
          requires:
            - install_dependencies
      - percy/finalize_all:
          requires:
            - run_tests
